### ISSUE TITLE
Weather and Wind icon too small

### ISSUE THREAD

**Issue by spcarluccio** [GuidoFe/weather-polybar-plugin#11]
Hi, nice polybar weather module.
How to make the weather and wind icons bigger ? I already use nerd fonts in my polybar bar.
The temp icon shows with the right size.

PS. Would be nice with the requirements mentions jq and bc packages.

**Comment by di-az** [comment]
The font for the weather icons is defined by: `WEATHER_FONT_CODE=4` which is picked up from the fonts defined by your polybar config

Just change the variable for a font with a bigger size

In case you don't know how to define fonts, check the polybar documentation: https://github.com/polybar/polybar/wiki/Fonts

**Comment by GuidoFe** [comment]
@Di-az that's correct, thank you for the explanation
