### ISSUE TITLE
Plugin disappears every update

### ISSUE THREAD

**Issue by AdamSacha** [GuidoFe/weather-polybar-plugin#14]
If I set the interval to 1 second it disappears and reappears every second.

**Comment by GuidoFe** [comment]
I've tried to reproduce your bug, but it works correctly for me. Have you tried to run polybar in the terminal? Do you get any error? Does it work correctly with larger intervals? What happen when you run the script alone, without polybar?

**Comment by AdamSacha** [comment]
Marking this as closed because I was just missing a dependency. Thanks for your help!
