### ISSUE TITLE
Weather description dosen't display accented characters

### ISSUE THREAD

**Issue by AdamSacha** [GuidoFe/weather-polybar-plugin#15]
As said in title the weather description just gets cut off when it gets to a character like 'ž'. It is probably an issue on line 318 (DESCRIPTION=`echo "$RESPONSE" | jq .weather[0].description | tr -d '"' | sed 's/.*/\L&/; s/[a-z]*/\u&/g'`" ") and could just be fixed by changing the sed to include the accented characters.

**Comment by GuidoFe** [comment]
Sorry if I respond to you only now. I've fixed the issue: the problem was that sed doesn't work well with unicode characters.
