### ISSUE TITLE
Temperature units (°C or °F) not showing 

### ISSUE THREAD

**Issue by armaninux** [GuidoFe/weather-polybar-plugin#16]
I'm on Fedora 38/i3wm, I haven't edited the .sh yet, the temperature units (whether metric or imperial) are not showing, I just see the temp icon followed by a bare number. I can't figure out the cause for this, any ideas?

**Comment by GuidoFe** [comment]
What is the output of `weather-plugin.sh` in the terminal?

**Comment by armaninux** [comment]
this is the full output (I only excluded location infos): 

{"coord":{"lon":---,"lat":---},"weather":[{"id":803,"main":"Clouds","description":"broken clouds","icon":"04d"}],"base":"stations","main":{"temp":24.2,"feels_like":24.22,"temp_min":22.31,"temp_max":26.38,"pressure":1012,"humidity":59},"visibility":10000,"wind":{"speed":0.89,"deg":269},"clouds":{"all":55},"dt":1684835591,"sys":{"type":2,"id":2019808,"country":"IT","sunrise":1684813417,"sunset":1684868105},"timezone":7200,"id":6535701,"name":"---","cod":---}

 %{T0}%{F#FFFFFF}%{F-}%{T-} Broken Clouds | %{F#F0C674}%{T0}%{T-}%{F-} 24%{T0}糖%{T-}

(cloud and thermometer icons are actually visible in the terminal, last icon is a Chinese character)

**Comment by GuidoFe** [comment]
I fixed the issue. Apparently NerdFont changed the icons' code

**Comment by armaninux** [comment]
Yeah I imagined it was about deprecated icons, thanks.

Sent from Proton Mail for iOS

Il mar, mag 23, 2023 alle 12:52, GuidoFe ***@***.***(mailto:Il mar, mag 23, 2023 alle 12:52, GuidoFe <<a href=)> ha scritto:
