### ISSUE TITLE
function no found in line 107

### ISSUE THREAD

**Issue by JuniorCorzo** [GuidoFe/weather-polybar-plugin#2]
I am trying to configure it but I get an error on line 107 saying that the function is not found.

**Comment by rwivie** [comment]
I had the same problem. Open the weather-plugin.sh file and you see that the file has 2 blank lines at the beginning. the line starting with #!/bin/bash needs to be the first line and then the script will work.

**Comment by GuidoFe** [comment]
Thanks! I've removed them
