### ISSUE TITLE
Inteer expression expected!

### ISSUE THREAD

**Issue by copypasteonly** [GuidoFe/weather-polybar-plugin#3]
The script does not work for me and running the script in a terminal gives this out
```
./weather-plugin.sh: line 117: [: "404": integer expression expected
./weather-plugin.sh: line 132: [: null: integer expression expected
./weather-plugin.sh: line 140: [: null: integer expression expected
./weather-plugin.sh: line 148: [: null: integer expression expected
./weather-plugin.sh: line 156: [: null: integer expression expected
./weather-plugin.sh: line 164: [: null: integer expression expected
./weather-plugin.sh: line 168: [: null: integer expression expected
./weather-plugin.sh: line 172: [: null: integer expression expected
./weather-plugin.sh: line 176: [: null: integer expression expected
./weather-plugin.sh: line 185: [: null: integer expression expected
./weather-plugin.sh: line 194: [: null: integer expression expected
./weather-plugin.sh: line 211: bc: command not found
./weather-plugin.sh: line 222: bc: command not found
./weather-plugin.sh: line 222: [: -eq: unary operator expected
./weather-plugin.sh: line 248: [: null: integer expression expected
./weather-plugin.sh: line 250: bc: command not found
./weather-plugin.sh: line 250: [: -eq: unary operator expected
 %{T4}%{F#f43753}%{F-}%{T-} Null | %{F#FFFFFF}%{T2}%{T-}%{F-} null%{T2}糖%{T-}
```

**Comment by GuidoFe** [comment]
It looks like the api is returning an error message. Update the script with the new version and run in the terminal `weather-plugin.sh -d`. Copy paste the output

**Comment by copypasteonly** [comment]
> It looks like the api is returning an error message. Update the script with the new version and run in the terminal `weather-plugin.sh -d`. Copy paste the output

Looks like the problem is on my end, instead of putting the city name I pasted the city code, changing it to the city name made it work although im not getting any icons only the words.

**Comment by GuidoFe** [comment]
> im not getting any icons

Are you using a Nerd Font? You need to set the correct font number in the script too

**Comment by copypasteonly** [comment]
> > 
> 
> Are you using a Nerd Font? You need to set the correct font number in the script too

Yep just found out that the font name I've used doesn't match with the one on fc-list. All is resolved now, thanks for the replies!
