### ISSUE TITLE
[Doc] Setting font

### ISSUE THREAD

**Issue by anoxie** [GuidoFe/weather-polybar-plugin#4]
Hi,
Thanks for you're work it seem's nice, but I can't config the weather icons. 

I have weather-icons install on my system but I don't really know how to setting it. What's 4 mean in WEATHER_FONT_CODE ? same issue for TEMP_FONT_CODE 

The script works, I have the forecast and the temp print.

Thanks.

**Comment by lars-vc** [comment]
Those are references to your font number in polybar, you can find more info here: https://github.com/polybar/polybar/wiki/Fonts#fonts

**Comment by anoxie** [comment]
Thanks for the reply. 

It still doesn't works. I certainly badly installed the weather-icons font...When I try to copy/paste an icon, it's not the one I want.
