### ISSUE TITLE
Feature: Get location by ip

### ISSUE THREAD

**Issue by lars-vc** [GuidoFe/weather-polybar-plugin#5]
Currently you have the location hardcoded, which is a bit annoying for laptops. So I propose getting to location based on ip, vpn users could then opt out of it by editting the script. How I did it locally:
```bash
tss=`curl -s ifconfig.me`  # == ip%
IP=${tss::-1}              # == ip
CITY_NAME=$(curl -s https://ipinfo.io/$IP | jq -r ".city")
COUNTRY_CODE=$(curl -s https://ipinfo.io/$IP | jq -r ".country")
```
If you like this idea ill make a pr

**Comment by GuidoFe** [comment]
It's a good idea! Just keep it optional and keep the hardcoded option as default
