### ISSUE TITLE
How can I solve unary operator expected?

### ISSUE THREAD

**Issue by zukrmn** [GuidoFe/weather-polybar-plugin#7]
**line 131 [-ne: unary operator expected**

![image](https://user-images.githubusercontent.com/105821940/189466702-b65c1652-06b8-418b-a049-67ae4ec9cd21.png)

**Comment by GuidoFe** [comment]
Write
```
echo $CODE
echo $RESPONSECODE
```
before that line, run the script and tell me what it prints
